package org.accp.office.pojo;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: vipbooks@qq.com
 * Version: 6.0.0
 */
/**
 * 审批状态表\r\n(APPROVALSTATE)
 * 
 * @author bianj
 * @version 1.0.0 2019-06-10
 */
public class ApprovalState {
    /** 版本号 */
    private static final long serialVersionUID = 3707557573210019870L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 报销状态id */
    private Integer approvalStateId;

    /** 报销状态名称 */
    private String approvalStateName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public ApprovalState() {
    }

    public ApprovalState(Integer approvalStateId, String approvalStateName) {
        this.approvalStateId = approvalStateId;
        this.approvalStateName = approvalStateName;
    }

    @Override
    public String toString() {
        return "ApprovalState{" +
                "approvalStateId=" + approvalStateId +
                ", approvalStateName='" + approvalStateName + '\'' +
                '}';
    }

    /**
     * 获取报销状态id
     * 
     * @return 报销状态id
     */
    public Integer getApprovalStateId() {
        return this.approvalStateId;
    }

    /**
     * 设置报销状态id
     * 
     * @param approvalStateId
     *          报销状态id
     */
    public void setApprovalStateId(Integer approvalStateId) {
        this.approvalStateId = approvalStateId;
    }

    /**
     * 获取报销状态名称
     * 
     * @return 报销状态名称
     */
    public String getApprovalStateName() {
        return this.approvalStateName;
    }

    /**
     * 设置报销状态名称
     * 
     * @param approvalStateName
     *          报销状态名称
     */
    public void setApprovalStateName(String approvalStateName) {
        this.approvalStateName = approvalStateName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}